{
    "odata.metadata": "https://ip-c613b574.ad.openearth.community:8443/dsdataserver/dsl.svc/OpenWorksCommonModel/5000107/OpenWorksCommonModel_LSSE2E-LSSE2E/NORWAY/$metadata#Wellbore",
    "value": [
        {
            "plot_name": "Water dpt. 367.00 m",
            "parent_wellbore_native_uid": null,
            "current_class": "EXPLORATION",
            "survey_location_type": null,
            "kick_off_tvd": null,
            "authorized_md": null,
            "create_user_id": "D70491",
            "formation_at_td": null,
            "native_uid": "1",
            "water_depth_unit": "meters",
            "security_on_off_flag": null,
            "plugged_back_md": 0,
            "data_acquisition_type": "UNKNOWN",
            "data_source": "LGC",
            "permit_no": "427-1",
            "plugged_back_md_unit": "meters",
            "current_status": "P&A MINR GAS&TR. OF OIL",
            "current_status_date": "2000-12-12T00:00:00.000",
            "bh_y_coordinate": "7252522.6129",
            "initial_status": "P&A MINR GAS&TR. OF OIL",
            "borehole_type": "UNKNOWN",
            "authorization_no": "NO PL095",
            "bh_crs": "ST_ED50_UTM32N_CM9NE",
            "bh_location_point": {
                "geo_type": "POINT",
                "x": [
                    "7.3287346978314805"
                ],
                "y": [
                    "65.38427844840977"
                ],
                "z": [],
                "x_unit": "dega",
                "y_unit": "dega",
                "x_unittype": "project coordinate",
                "y_unittype": "project coordinate"
            },
            "y_coordinate": "7252522.34885895",
            "bh_x_coordinate": "422412.7391",
            "total_drilling_cost": null,
            "update_user_id": "SVCOW",
            "elevation_unit": "meters",
            "bh_xy_unit": "meters",
            "currency": "UNKNOWN",
            "alternate_uid": "1",
            "drilling_operator": "CONOCO",
            "x_coordinate": "422581.990120904",
            "well_geometry_desc": null,
            "authorized_md_unit": null,
            "farm_out": null,
            "data_acquisition_company": "UNKNOWN",
            "permit_date": null,
            "completion_date": "1984-01-12T00:00:00.000",
            "alternate_wellbore_uwi": null,
            "symbol": 62,
            "wellbore_name": "6507/7-1",
            "restricted_data_ind": "N",
            "parent_wellbore_uwi": null,
            "well_native_uid": "1",
            "create_date": "2002-03-15T09:54:00.000",
            "wellbore_uwi": "NO 6507/7-1",
            "trajectory_shape": "UNKNOWN",
            "kick_off_tvd_unit": null,
            "borehole_no": null,
            "date_data_released": "1984-12-01T00:00:00.000",
            "update_date": "2024-04-03T13:52:38.000",
            "wellbore_number": "7-1",
            "elevation_type": "KB",
            "total_depth": 4825,
            "ground_elevation": null,
            "field_native_uid": "309",
            "authorized_tvd": null,
            "water_depth_datum": null,
            "internal_drilling_cost": null,
            "remark": "Letebronn, P & A, Spor av gass. (Heidrun field). QC 970516",
            "alternate_wellbore_name": "6507/7-1",
            "initial_class": "EXPLORATION",
            "kick_off_depth": null,
            "water_depth": null,
            "xy_unit": "meters",
            "ground_elevation_unit": "meters",
            "elevation": 25,
            "crs": "ST_ED50_UTM32N_CM9NE",
            "spud_date": "1984-08-10T00:00:00.000",
            "field_name": "HALTENBANKEN",
            "well_operator": "CONOCO",
            "authorized_tvd_unit": null,
            "user_def2": null,
            "user_def1": null,
            "total_depth_unit": "meters",
            "well_uwi": "NO 6507/7-1",
            "kick_off_depth_unit": "meters",
            "uwi_type": "CDS"
        }
    ]
}